[package]
name = "powlib"
version = "0.1.0"
edition = "2024"

[lib]
name = "pow"
crate-type = ["cdylib"]

[dependencies]
base64 = "0.22.1"
hmac = "0.12.1"
json = "0.12.4"
libc = "0.2.177"
once_cell = "1.21.3"
rand = "0.9.2"
sha2 = "0.10.9"
